### PR TITLE
Remove support for Python 3.6

### LINKED ISSUE #49: Drop Python 3.6 support after 2021-12-23
Need to drop support at that time. Probably should push a release out before then if necessary.

[PEP 494 -- Python 3.6 Release Schedule](https://www.python.org/dev/peps/pep-0494/)

### PR DESCRIPTION
**Pull request by francium**
Closes #49 

Let me know if I missed something here.

This is going to conflict with my other PR due to changelog. I'll fix the conflict after that PR is merged.

### CODE REVIEW

**Comment by wbolster** [comment]
i've fixed the merge conflict, and also removed `py36` from `tox.ini` since #80 was merged in the mean time

**Comment by wbolster** [comment]
lgtm but github status check waits for a 3.6 check which will never come.

maybe this needs some repo settings to be changed, but i don't have access to those.


@francium @dbrgn 
https://github.com/orgs/rustedpy/people

perhaps you can make me an owner (not member) of this github org?

**Review by wbolster — APPROVED** [review]

**Comment by dbrgn** [comment]
@wbolster I made you an admin of this repo, you should be able to change the settings now!

**Comment by wbolster** [comment]
ack, fixed the branch protection settings to no longer required the now-deleted check, and added py310 while at it

**Pull request merged**
