### PR TITLE
Add a `.value_safe()` method (name is not great, open to suggestions 😆 )

### PR DESCRIPTION
**Pull request by noxasaxon**
I may be mistaken, but I haven't seen a method for accessing an Ok value that only exists on the `Ok` class. For instance using `Err.ok()` won't raise errors in pylance as it returns `None` which is falsy, but not a type-checking error unless it happens to be provided somewhere that won't accept `None`.

With a method (or we could use a property, not sure if thats better in this situation) for accessing `self._value` that only exists on `Ok()` classes, pyright/mypy can typecheck any access of value.

### CODE REVIEW

**Comment by francium** [comment]
If I understand you correctly you're talking about a situation like this?
```
r1: Result[int, str] = foo()
r1.value_safe()
   ^^^^^^^^^^    Cannot access member "value_safe" for type "Err[str]"
                   Member "value_safe" is unknown (Pyright reportGeneralTypeIssues)

if isinstance(r1, Ok):
    r1.value_safe()
else:
    r1.value_safe();
       ^^^^^^^^^^     Cannot access member "value_safe" for type "Err[str]"
                        Member "value_safe" is unknown (Pyright reportGeneralTypeIssues)
```

**Comment by francium** [comment]
How about `ok_safe`? and `err_safe`?
I don't write too much Python these days so I may not be the best person to discuss the best option here.

@wbolster or @dbrgn any thoughts on this?

**Comment by noxasaxon** [comment]
yeah that sounds like a better name for sure 👍

**Comment by wbolster** [comment]
is this the same as #37?

**Comment by noxasaxon** [comment]
> is this the same as #37?

Yeah i think it is, actually!

**Comment by francium** [comment]
@noxasaxon If you're able to finish this PR off, I think we've got at least some agreement on this being an acceptable change to make. Please see the comments in https://github.com/rustedpy/result/issues/37#issuecomment-1243107843. Thanks

**Comment by briandw** [comment]
@francium What's left to do on this PR?

**Comment by francium** [comment]
I'll take over this PR. It's been a while, so I've posted a comment to clarify something in #37.
Once that's clear, I'll make a PR to finish off this work

We'll make a new PR, closing this PR

**Pull request closed without merging**
